### PR TITLE
Fix issue 38

### LINKED ISSUE #38: Keyboard shortcuts break comment entry for a recording
The recently added keyboard shortcuts when viewing a recording remain active while typing a comment. This means that you can easily end up activating shortcut actions while typing!

### PR DESCRIPTION
**Pull request by CameronRP**
closes #38

### CODE REVIEW

File: public/javascripts/viewRecording.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ var recordingsApiUrl = api + '/api/v1/recordings'
 var recording = null;
 
 document.onkeypress = function (e) {
+  if (document.activeElement.tagName != 'BODY') { return; }
```
Comment (mjs) [inline public/javascripts/viewRecording.js]: will that tag name always be upper case? (i.e. should we be forcing it to upper case before checking?)
will the active element *always* be the body if an input field isn't selected?

Comment (CameronRP) [reply public/javascripts/viewRecording.js]: I would assume that the tag name will always be upper case but can change that.
I just chose to use 'BODY' as I'm not too sure on what all the input tag names might be in the future. It looks like the only ones that are an input right now are 'INPUT' and 'SELECT'. Should I just change it to ignore it when this is the case?

Comment (mjs) [reply public/javascripts/viewRecording.js]: I don't know enough about how `activeElement` works in all browsers to be sure. I guess leave it as is and see how it goes. At worst it'll disable the shortcuts more than it should.

Forcing the tag name to upper or lowercase before comparing is probably a good idea though.

**Review by mjs — APPROVED** [review]
