### PR TITLE
Check for, and resolve, api address ending in /

### LINKED ISSUE #4: API requests fail if server URL in config ends with slash
If `server.api` is set to a URL which ends with a slash, API requests are made with double slashes (e.g. //api/v1/Users) and fail. The config parsing code should normalise the URL.

### PR DESCRIPTION
**Pull request by arthurmcgregor**
Fixes #4 - hopefully in a sensible place in a sensible way?!

### CODE REVIEW

File: Server.js [hunk 1]
```diff
@@ -11,6 +11,10 @@ try {
 
 var log = require('./logging');
 
+if (config.server.api.slice(-1) === '/') {
```
Comment (mjs) [inline Server.js:14]: `config.server.api.endsWith('/')` would work too. Either way.

**Review by mjs — DISMISSED** [review]
Thanks.

File: Server.js [hunk 2]
```diff
@@ -11,6 +11,10 @@ try {
...
+  config.server.api = config.server.api.slice(0,-1);
+}
+
```
Comment (mjs) [inline Server.js:17]: I wonder if this would be better done inside config.js? (in `loadConfig`)

That way any code that looks at the configuration gets a consistent view the API URL.

Comment (arthurmcgregor) [reply Server.js:17]: I'm not sure what you mean. Where/what is `loadConfig`? Is it likely that anything else will read from config.js?

Comment (mjs) [reply Server.js:17]: `loadConfig()` is in `/config.js`. It's what is called to read the configuration file. There would be the perfect place to normalising the API URL.

Comment (arthurmcgregor) [reply Server.js:17]: Ah I finally found loadConfig().... but in cacophony-api! It doesn't exist in cacophony-web

Comment (mjs) [reply Server.js:17]: Sorry to mislead you! The code is fine as is.

**Review by mjs — APPROVED** [review]
